### ISSUE TITLE
Pingserver

### ISSUE THREAD

**Issue by mixisbad** [Akiira/MUD-Client#1]
I don't think we should open ping server on client side.
It means that client without public IP or is behind router will not be able to get pinged.
We may try a special type of server response similar to the redirect one that force client to answer back instantly.

**Comment by Akiira** [comment]
That is a good point, I did not think of that. I originally had it that way too but the code did not feel very nice.

In order to keep the code somewhat clean, I think I will combine both methods into one. I will have the Server host a separate ping server and send a special message to the client, informing the client that it should connect to it and send pings. 

Though, I have recently been learning about Go Channels, and it may be possible to use them in a similar manner to what I did for trading. Then it could all be over one connection.

I will think about it and implement one method later this weekend.

**Comment by Akiira** [comment]
I fixed this.
